### ISSUE TITLE
Hoop Unbound not able to use their signature move (Hyperspace Fury). 

### ISSUE THREAD

**Issue by stewwen** [jflec/bcg-atm#28]
I managed to fix it on my own client, I just wanted to let yall know so that you may also fix it in the upcoming update.

just repleace the old json file with the one attached here :D

![image](https://github.com/user-attachments/assets/37bafe15-4e57-4978-9e26-f9df7c6054c6)

[hoopaunbound.json](https://github.com/user-attachments/files/17344774/hoopaunbound.json)

**Comment by stewwen** [comment]
[hoopaunbound.json](https://github.com/user-attachments/files/17344769/hoopaunbound.json)

**Comment by jflec** [comment]
Will fix in next update!

**Comment by jflec** [comment]
Fixed in 1.2.0
