### ISSUE TITLE
Bugged Pawmo -> Pawmot Evolution

### ISSUE THREAD

**Issue by AcrobatTheDragon** [jflec/bcg-atm#6]
My fellow players and I have been experiencing some issues regarding evolving Pawmo into Pawmot. No matter how many step we take with it, it will not evolve into Pawmot.

**Comment by jflec** [comment]
So I was going to just remove the requirement, however I was able to get it to evolve. The Pokemon itself needs to walk 1000 blocks, I don't think teleporting counts.
