### ISSUE TITLE
Lunala cannot spawn in the end due to can see sky

### ISSUE THREAD

**Issue by Zexxx** [jflec/bcg-atm#8]
"canSeeSky": true,
This condition is impossible to achieve in the end as its exclusive to the overworld.

`{
  "enabled": true,
  "neededInstalledMods": [],
  "neededUninstalledMods": [],
  "spawns": [
    {
      "id": "lunala-1",
      "pokemon": "lunala",
      "type": "pokemon",
      "context": "grounded",
      "bucket": "ultra-rare",
      "level": "70",
      "weight": 0.2,
      "condition": {
        "canSeeSky": true,
        "biomes": ["#cobblemon:is_spooky"],
        "timeRange": "night"
      }
    },
    {
      "id": "lunala-2",
      "pokemon": "lunala",
      "type": "pokemon",
      "context": "grounded",
      "bucket": "ultra-rare",
      "level": "70",
      "weight": 0.4,
      "condition": {
        "canSeeSky": true,
        "biomes": ["#minecraft:is_end"]
      }
    }
  ]
}`

**Comment by jflec** [comment]
Fixed in 1.1.0
